version: "3.6"

services:
  compress-image:
    container_name: my-lambda-container
    build: .
    volumes:
      - $HOME/.aws/:/root/.aws/
    ports:
      - "9000:8080"
    env_file:
      - .env
